@echo off
setlocal EnableExtensions EnableDelayedExpansion

set "log_dir=C:\Users\User\Desktop\logs\robocal_output"
set "return_code=1"

rem Find the newest log generated by RoboCal.
set "log_file="
for /f "delims=" %%F in ('dir /b /a-d /o-d /t:c "!log_dir!\log_file_*.log" 2^>nul') do (
	if not defined log_file set "log_file=!log_dir!\%%F"
)

rem Prefer the first number from the last "Error Codes: [...]" line.
if defined log_file (
	set "log_result_found="
	for /f "tokens=2 delims=[" %%A in ('findstr /c:"Error Codes:" "!log_file!"') do (
		for /f "tokens=1 delims=," %%B in ("%%A") do set "return_code=%%B"
		set "log_result_found=1"
	)

	rem Some fatal failures only write a final line such as "Exit code 204".
	if not defined log_result_found (
		for /f "delims=" %%A in ('findstr /r /c:"Exit code [0-9][0-9]* *$" "!log_file!"') do (
			for %%B in (%%A) do set "return_code=%%B"
			set "log_result_found=1"
		)
	)

	rem A completed passing run ends with "Safe to unload." and returns zero.
	if not defined log_result_found (
		findstr /c:"Safe to unload." "!log_file!" >nul
		if not errorlevel 1 (
			set "return_code=0"
			set "log_result_found=1"
		)
	)
	echo Log file: !log_file!
) else (
	echo Warning: No RoboCal log file was found in !log_dir!
)

rem Remove spaces that may surround the extracted number.
set "return_code=!return_code: =!"
set errorlevel=!return_code!
echo Return code: !return_code!
exit /b !return_code!