@echo off
setlocal EnableExtensions EnableDelayedExpansion

set "log_dir=C:\Users\User\Desktop\logs\robocal_output"

robocal.exe --single_run --skip_audio=True --skip_wfsc=True --skip_dgc=True --skip_dcc=False --debug %*
set "return_code=!ERRORLEVEL!"

rem Find the newest log generated by RoboCal.
set "log_file="
for /f "delims=" %%F in ('dir /b /a-d /o-d /t:c "!log_dir!\log_file_*.log" 2^>nul') do (
	if not defined log_file set "log_file=!log_dir!\%%F"
)

rem Use the first number from the last "Error Codes: [...]" line.
if defined log_file (
	for /f "tokens=2 delims=[" %%A in ('findstr /c:"Error Codes:" "!log_file!"') do (
		for /f "tokens=1 delims=," %%B in ("%%A") do set "return_code=%%B"
	)
	echo Log file: !log_file!
) else (
	echo Warning: No RoboCal log file was found in !log_dir!
)

rem Remove spaces that may surround the extracted number.
set "return_code=!return_code: =!"
echo Return code: !return_code!
exit /b !return_code!