; --------------------------------------------------------------------------
; INI file for USB31-diags.exe, Rev: 2.00uP15
; --------------------------------------------------------------------------
; Set the check range for VCC
; ==============================
; SPEC VCC_HI VCC_LO  I_HI  I_LO
; ---- ------ ------ ----- -----
  VC 1   5300   4000   900   500
  VC 2   5300   4000  3000  2000
  VC 3   5300   4000  2000  1500
  VC 4   5300   4000  1500  1000
  VC 5   5300   4000   500   200
; ---- ------ ------ ----- -----

; Super Speed Configuration
; =========================
; No isTest Speed CON BULK INT ISO VCC&I  Jig Access_Address Modify_Data Location  Driver_Information                                
; -- ------ ----- --- ---- --- --- ----- ---- -------------- ----------- --------- --------------------------------------------------
   1      1 SUPER   1    1   1   1     0 Mini 0              0           0         PEGAUSB,[V,D]=[8086,34ed], [Port]=[13-2]          
; -- ------ ----- --- ---- --- --- ----- ---- -------------- ----------- --------- --------------------------------------------------

; High Speed Configuration
; ========================
; No isTest Speed CON BULK INT ISO VCC&I  Jig Access_Address Modify_Data Location  Driver_Information                                
; -- ------ ----- --- ---- --- --- ----- ---- -------------- ----------- --------- --------------------------------------------------
   1      1  HIGH   1    1   1   1     0 Mini 0              0           0         PEGAUSB,[V,D]=[8086,34ed], [Port]=[1-2]           
; -- ------ ----- --- ---- --- --- ----- ---- -------------- ----------- --------- --------------------------------------------------

; Full Speed Configuration
; ========================
; No isTest Speed CON BULK INT ISO VCC&I  Jig Access_Address Modify_Data Location  Driver_Information                                
; -- ------ ----- --- ---- --- --- ----- ---- -------------- ----------- --------- --------------------------------------------------
   1      1  FULL   1    1   1   1     0 Mini 0              0           0         PEGAUSB,[V,D]=[8086,34ed], [Port]=[1-2]           
; -- ------ ----- --- ---- --- --- ----- ---- -------------- ----------- --------- --------------------------------------------------

; Low  Speed Configuration
; ========================
; No isTest Speed CON BULK INT ISO VCC&I Location  Driver_Information
; -- ------ ----- --- ---- --- --- ----- --------- -----------------------------------------------------------------------------
   1      1   LOW   1    0   0   0     0 N/A                                                         
; -- ------ ----- --- ---- --- --- ----- --------- -----------------------------------------------------------------------------

