; --------------------------------------------------------------------------
; INI file for USB30-diags.exe
; --------------------------------------------------------------------------

; Set the check range for VCC
; ===========================
VCC_HI= 5300
VCC_LO= 4500
USB3_I_HI= 900
USB3_I_LO= 500
USB_I_HI= 500
USB_I_LO= 200

; Super Speed Configuration
; =========================
; No isTest Speed CON BULK INT ISO VCC VCC_HI VCC_LO Location_Paths                                               Driver_Information
; -- ------ ----- --- ---- --- --- --- ------ ------ ------------------------------------------------------------ ------------------------------------------------------------
   1      1 SUPER   1    1   1   1   1 VCC_HI VCC_LO 0                                                            PEGAUSB, 5&1EAC217B&0&18                                    
; -- ------ ----- --- ---- --- --- --- ------ ------ ------------------------------------------------------------ ------------------------------------------------------------

; High Speed Configuration
; ========================
; No isTest Speed CON BULK INT ISO VCC VCC_HI VCC_LO Location_Paths                                               Driver_Information
; -- ------ ----- --- ---- --- --- --- ------ ------ ------------------------------------------------------------ ------------------------------------------------------------
   1      1  HIGH   1    1   1   1   1 VCC_HI VCC_LO 0                                                            PEGAUSB, 5&1EAC217B&0&2                                     
; -- ------ ----- --- ---- --- --- --- ------ ------ ------------------------------------------------------------ ------------------------------------------------------------

; Full Speed Configuration
; ========================
; No isTest Speed CON BULK INT ISO VCC VCC_HI VCC_LO Location_Paths                                               Driver_Information
; -- ------ ----- --- ---- --- --- --- ------ ------ ------------------------------------------------------------ ------------------------------------------------------------
   1      1  FULL   1    1   1   1   1 VCC_HI VCC_LO 0                                                            PEGAUSB, 5&1EAC217B&0&2                                     
; -- ------ ----- --- ---- --- --- --- ------ ------ ------------------------------------------------------------ ------------------------------------------------------------

; Low  Speed Configuration
; ========================
; No isTest Speed CON BULK INT ISO VCC VCC_HI VCC_LO Location_Paths                                               Driver_Information
; -- ------ ----- --- ---- --- --- --- ------ ------ ------------------------------------------------------------ ------------------------------------------------------------
   1      1   LOW   1    0   0   0   0      0      0 N/A                                                                                                                      
; -- ------ ----- --- ---- --- --- --- ------ ------ ------------------------------------------------------------ ------------------------------------------------------------

